### ISSUE TITLE
Edge timings

### ISSUE THREAD

**Issue by SamTov** [zincware/ZnTrack#115]
One nice property of resource graphs and network theory is the ability to time stages. It would be quite a nice feature to add node execution timing and so-called `meta-data` to each node. This could lead to interesting analysis of the graph and possible identification of workflow failures or bottlenecks.

### Addition

This is actually an interesting step in the direction of including loops in a computational graph. Whilst the full graph should remain acyclic, it could be possible to have specific nodes in loops to solve some problem. 

What we would then have is a dynamic rather than a static graph.

**Comment by PythonFZ** [comment]
> This is actually an interesting step in the direction of including loops in a computational graph. Whilst the full graph should remain acyclic, it could be possible to have specific nodes in loops to solve some problem.
> 
> What we would then have is a dynamic rather than a static graph.

Is this related to this Issue or more #113 ?

For the node execution time I could think about some possible implementations (if you can think about another one, let me know):

```py
@Node(timeit=True)
class HelloWorld:
   def run(self):
      pass
```

```py
@zn.timeit
@Node()
class HelloWorld:
   def run(self):
      pass
```

or/and 

```py
@Node()
class HelloWorld:
   def run(self):
      pass

hello_world = HelloWorld()
hello_world(timeit=True)
```

This is more or less already possible with some arguments, such as `always_changed`.

For the `meta-data` it would be interesting to know what would happen to this data? Should it be used in another Node, is it a metric for the entire graph that is used later for evaluation? Is it some data that should should be changeable but not trigger a node rerun - this might be useful in some scenarios.

**Comment by SamTov** [comment]
I think the `@Node(time=True)` is probably the nicest approach. What I would consider is a set of Graph analysis tools which can be enabled in the node calls. At the end of computations you call call some of this information to better analyse your workflow.

**Comment by PythonFZ** [comment]
Maybe then I would propose another possibility.
```py
@Node()
class HelloWorld:
    
    @zn.timeit
    def run(self):
        pass
        # do stuff
    
    @zn.timeit
    def some_other_method(self):
        pass
```

This could then produce a metric called `HelloWorld.run.timeit` and `HelloWorld.some_other_method.timeit`.
I would handle the outcomes either as metrics or outs. This way they would be available via the typical `dvc metrics show` methods. The one benefit of having the `timeit=True` in the call is that it can easier be enabled, disabled. But we could have a general `config.track_metadata = True` which handles if the `timeit` should be run or not.

**Comment by SamTov** [comment]
I think that is a good but also seperate thing. It would be good to have one thing that does measure the time of the full node but also a decomposition option which splits it further into component-wise contributions like you describe here.

**Comment by PythonFZ** [comment]
This would then be the zn.tieming decorator on the run method. It could be a more general API compared to splitting it up into the Node argument and the decorators? If we would like the split, I would argue that going for the decorator might be better generalisable. If we dont need the Split the node argument might be simpler. In the end we can have both, because I would wrap the run in the decorator anyways.

**Comment by SamTov** [comment]
I think long term the split is good but short term just the run would already be quite a nice feature. What we could do is break down several things that we can measure about the nodes and put together some module for that and how to report it all. This could be quite nice thing to have. Timing the run method could just be the start of it.
