### ISSUE TITLE
zn.plots try/except issue

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnTrack#337]
https://github.com/zincware/ZnTrack/blob/4d4c75b53cadb688d031ce4265bf6b1a6a066f0e/zntrack/zn/plots.py#L42-L43

@laigner

**Comment by PythonFZ** [comment]
Can you give an example where this fails and do you see any issues that could arise from just returning None instead?

**Comment by laigner** [comment]
It fails using Nodes as `zn.Nodes()` within another Node.
e.g. In the active learner using the `ComparisonBase` which has `zn.plots()`
